nav:
  - index.md
  - Stories:
      - story/index.md
      - 01 An Italian Data Journey: story/E6263/index.md
      - 02 A Deep Dive into NFDI4Culture's Integration Workflows: story/E6477/index.md
  - Contribute: contribute.md
  - SPARQL Exploration: "/shmarql"